### ISSUE TITLE
Problem with setup-Please help!

### ISSUE THREAD

**Issue by hamed-az** [davispuh/MySQL-for-Python-3#3]
hi! Mr. Davis
I have a problem with the setup. pyconfig.h can't open include file "io.h" but i have MSVC2010 installed and in the path.
this is the error i get:
c:\program files (x86)\python\include\pyconfig.h(68) : fatal error C1083: Cannot
 open include file: 'io.h': No such file or directory
error: command 'cl.exe' failed with exit status 2

i have win7 x64, python 3,mysql 5.5 (in xampp),msvc2010

please help
TNX IN ADVANCE!

**Comment by davispuh** [comment]
did you follow [Install on Windows](/davispuh/MySQL-for-Python-3/wiki/Install-on-Windows) ?

I just checked everything (with newest python 3.3.1 for x64) and works perfectly out-of-box :)

Seems it didn't found VC include files, I suggest to try installing Windows SDK 7.1

**Comment by hamed-az** [comment]
thanks for reply
i've installed SDK also (ver7.0) but i didn't follow "install on windows" page.
i'll check that. hope to work :)
thank you

**Comment by hamed-az** [comment]
hi again
finally i succeeded :)
first, i was using win command prompt whereas you've mentioned using sdk cmd (step 10). that was the reason it couldn't find "io.h", but still it didn't work in relation with _mysql. therefore i installed mysql seperately from xampp and it worked. :)
but why it don't work with xampp? i'll find it.
thank you very much
best regards

**Comment by davispuh** [comment]
it might be that XAMP doesn't include required MySQL include/lib files, inside `site.cfg` you should have wrote path to it where it's located, there should be `include` and `lib` dirs.

Anyway good that you got it working, I'm closing this :)
